### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by ColCarroll** [jax-ml/oryx#19]
Hey! New to `poetry` so maybe I'm missing something, but I couldn't get `bazel` working, nor could I find any `BUILD` files. One thing that _did_ work surprisingly well was `pytest-cov` ([docs](https://pytest-cov.readthedocs.io/en/latest/)), and using 
```bash
poetry run pytest-cov
```
Lets me know there's 95% test coverage, and that all but 4 tests pass on my machine. Those remaining 4 fail with
```python
ValueError: compiling computation that requires 2 logical devices, but only 1 XLA devices are available...
```

Seems like it wouldn't be too much work to set this up on CI if there's interest (probably just using GH actions and marking xfail on the failing tests). LMK if there's interest and I can put a PR together (not sure if tests are already being run elsewhere!)

**Comment by sharadmv** [comment]
Yea we should update the readme here. `bazel` used to work when Oryx was part of TFP but its new set up removes all the BUILD files so `pytest` should be used instead. However, I think a couple tests need to be skipped (those failures you found). I'll send a PR that fixes this.
