### ISSUE TITLE
Incompatible with latest jax version

### ISSUE THREAD

**Issue by aniquetahir** [jax-ml/oryx#24]
I get the following error when running on the latest jax release:
`AttributeError: module 'jax.interpreters.partial_eval' has no attribute 'remat_call_p'`

jax version: jax-0.3.25 jaxlib-0.3.25+cuda11.cudnn82

**Comment by ColCarroll** [comment]
Hey! 

Looks like this was fixed in https://github.com/jax-ml/oryx/pull/11 -- there has not been a new pypi release since then, but I believe 

```
pip install git+https://github.com/jax-ml/oryx.git
```

should install from HEAD.

**Comment by aniquetahir** [comment]
Appears to be working now. However for some reason if Oryx is installed after jax, it uninstalls the latest jax and replaces it with an older version:
```
Building wheels for collected packages: oryx
  Building wheel for oryx (pyproject.toml) ... done
  Created wheel for oryx: filename=oryx-0.2.4-py3-none-any.whl size=203765 sha256=b4e9fe92ff1cef929a4ccdafe16220471c7210ec4c7a24a7d65c232f401f7481
  Stored in directory: /tmp/pip-ephem-wheel-cache-yczgh0oy/wheels/15/00/61/61ca9f91a48161c5b0d49f2eed1873ff6f8f9ca6ee0522166d
Successfully built oryx
Installing collected packages: jaxlib, jax, oryx
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.3.25+cuda11.cudnn82
    Uninstalling jaxlib-0.3.25+cuda11.cudnn82:
      Successfully uninstalled jaxlib-0.3.25+cuda11.cudnn82
  Attempting uninstall: jax
    Found existing installation: jax 0.3.25
    Uninstalling jax-0.3.25:
      Successfully uninstalled jax-0.3.25
Successfully installed jax-0.3.21 jaxlib-0.3.20 oryx-0.2.4
```
To get around this I reinstall jax after installing oryx.

**Comment by ColCarroll** [comment]
Should we perhaps loosen `pyproject.toml` to use

```
jax = "^0.3.21"
jaxlib = "^0.3.20"
```

seems like if newer JAX really breaks things, it is worth fixing, bumping the versions, and cutting a new release.

**Comment by sharadmv** [comment]
In the past that was true, but these days JAX doesn't seem to break Oryx as often. I agree, we should relax it.

**Comment by sharadmv** [comment]
This should be fixed with the newest Oryx release.
